name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Build
        run: pnpm build

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Run tests
        run: pnpm test

      - name: Test coverage
        run: pnpm test:coverage

      - name: Coverage validation
        run: |
          # Check if coverage meets minimum requirement (90%)
          node -e "
            const fs = require('fs');
            if (fs.existsSync('coverage/coverage-final.json')) {
              const coverage = JSON.parse(fs.readFileSync('coverage/coverage-final.json', 'utf8'));
              
              // Calculate total coverage from all files
              let totalStatements = 0;
              let coveredStatements = 0;
              
              Object.values(coverage).forEach(file => {
                if (file.s) {
                  const statements = Object.values(file.s);
                  totalStatements += statements.length;
                  coveredStatements += statements.filter(count => count > 0).length;
                }
              });
              
              const totalCoverage = totalStatements > 0 ? (coveredStatements / totalStatements) * 100 : 0;
              
              console.log('Total coverage:', totalCoverage.toFixed(2) + '%');
              console.log('Covered statements:', coveredStatements + '/' + totalStatements);
              
              if (totalCoverage < 90) {
                console.error('❌ Coverage below 90% requirement:', totalCoverage.toFixed(2) + '%');
                process.exit(1);
              }
              
              console.log('✅ Coverage requirement met:', totalCoverage.toFixed(2) + '%');
            } else {
              console.log('⚠️ Coverage report not found');
            }
          "

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.node-version }}-${{ github.sha }}
          path: coverage/
          retention-days: 30

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check build artifacts
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "❌ dist/index.js not found"
            exit 1
          fi
          
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ dist/index.d.ts not found"
            exit 1
          fi
          
          echo "✅ Build artifacts verified"

      - name: Validate package.json
        run: |
          node -e "
            const pkg = require('./package.json');
            
            console.log('Package name:', pkg.name);
            console.log('Package version:', pkg.version);
            console.log('Main entry:', pkg.main);
            console.log('Types entry:', pkg.types);
            
            if (!pkg.main || !pkg.types) {
              console.error('❌ Missing main or types in package.json');
              process.exit(1);
            }
            
            // Check if dist files exist
            const fs = require('fs');
            if (!fs.existsSync(pkg.main)) {
              console.error('❌ Main file not found:', pkg.main);
              process.exit(1);
            }
            
            if (!fs.existsSync(pkg.types)) {
              console.error('❌ Types file not found:', pkg.types);
              process.exit(1);
            }
            
            console.log('✅ Package validation passed');
          "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            dist/
            package.json
            README.md
          retention-days: 7
